feat: 🎸 Generators dto's
e-square-io/angular-cli-gui pull request #71
Opened 2023-02-26 12:42 UTC by iYadgar

created script to generate all generators dto's according to angular's cli schema.json

✅ Closes: 70

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: [CONTRIBUTING.md](CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information

2023-02-26 16:28 UTC, eladzipper96 commented on script.js
> +  '/Users/idan.yadgar/angular-cli-e-square/angular-cli/packages/schematics/angular';
Is this left by mistake?

2023-02-26 20:23 UTC, OmerGronich requested changes
Cool!

Few questions

When is the script going to run? Are we going to run it periodically? 
And how are we going to make sure that the DTO's it generates are actually correct? We need to write a lot of tests for this script.

2023-02-26 20:23 UTC, OmerGronich commented on script.js
> +const { readdirSync, readFileSync, writeFile } = require('fs');
Why not make this a TS file?

2023-02-26 20:23 UTC, OmerGronich commented on script.js
> +}
export it to a generic place for utils

2023-02-26 20:23 UTC, OmerGronich commented on script.js
> +}
```suggestion
function capitalize(s) {
  return s[0].toUpperCase() + s.slice(1).toLowerCase();
}
```

2023-02-26 20:23 UTC, OmerGronich commented on script.js
> +  '/Users/idan.yadgar/angular-cli-e-square/angular-cli-gui/apps/cli-daemon/src/app/generators/dto/generators';
?

2023-02-28 13:55 UTC, ronnetzer reviewed
Continuing my question in your HLD, what about "workspace schematics"? (Is it possible with ng cli?), what about 3rd party schematics? how do we plan to "discover" schematics on run-time? as I understand this is a compile-time thing, we run this script before we deploy a new version.
if we do need to do this stuff in run-time, there is no point of generating DTOs, we should parse schema.json and map it to a general DTO, something like `SchematicArgument[]` (maybe there's an interface from angular we can use) when the client requests for the available arguments of some schematic. I guess we can also generate the class in run-time in order to use it's class-validator features when BE receives an execute/generate command

2023-03-01 14:22 UTC, closed without merging